version: '2.3'


name: 'jenkins-sonarqube'

services:

  # docker jenkins-server
  jenkins-server-sonar:
    container_name: jenkins-server-sonar
    image: jenkins/jenkins:lts-jdk17
    volumes:
      - data:/opt/data
    networks:
      - cicdnetwork
    expose:
      - 22
      - 50000
    ports:
      - 5000:8080

  # docker ssh-jenkins_agent_1
  jenkins-agent-1:
    container_name: jenkins-agent-sonar-1
    build:
      context: ../docker-agents/ssh-agent-1
      dockerfile: Dockerfile
    depends_on:
      - jenkins-server-sonar
    volumes:
      - data:/opt/agent_1
    networks:
      - cicdnetwork
    expose:
      - 22
    ports:
      - 1000:22

  # docker ssh-jenkins_agent_2
  jenkins-agent-2:
    container_name: jenkins-agent-sonar-2
    build:
      context: ../docker-agents/ssh-agent-2
      dockerfile: Dockerfile
    depends_on:
      - jenkins-server-sonar
    volumes:
      - data:/opt/agent_2
    networks:
      - cicdnetwork
    expose:
      - 22
    ports:
      - 22:22

  # docker mysql-database
  # MYSQL_URL=jdbc:mysql://ubuntu-mysql/docker_cicd
  ubuntu-mysql-sonar:
    container_name: ubuntu-mysql-sonar
    build:
      context: ../mysql-db/
      dockerfile: Dockerfile
    volumes:
      - mysqlData:/var/lib/mysql
      - mysqlConfig:/etc/mysql/conf.d
    networks:
      - cicdnetwork
    expose:
      - 3306
      - 22
    ports:
      - 30306:3306

  #jdbc:postgresql://postgres-sql-server/sonar
  postgres-sql-server:
    container_name: postgres-sql-server
    build:
      context: ../postgres-sql/
      dockerfile: Dockerfile
    volumes:
      -  postgresql:/var/lib/postgresql
      -  postgresql_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
      - 9090:8080
    networks:
      - cicdnetwork
  
  sonar-qube-server:
    container_name: sonar-qube-server
    depends_on:
      - postgres-sql-server
    build:
      context: ../sonar-cube/
      dockerfile: Dockerfile
    volumes:
     - sonarqube_data:/opt/sonarqube/data  
     - sonarqube_extensions:/opt/sonarqube/extensions
     - sonarqube_logs:/opt/sonarqube/logs
    expose:
      - 9000
    ports:
      - "9000:9000"  
    networks:
    - cicdnetwork

networks:
  cicdnetwork:

volumes:
  data:
  mysqlData:
  mysqlConfig:
  postgresql:
  postgresql_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:


